services:
  web:
    ports:
      - '${LOCAL_WEB_PORT:-4000}:4000'

  nginx:
    image: nginx:1.29-alpine
    depends_on:
      - web
    ports:
      - '${LOCAL_NGINX_PORT:-8080}:80'
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
